# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flyio
from flyio.models.check_status import CheckStatus  # noqa: E501
from flyio.rest import ApiException


class TestCheckStatus(unittest.TestCase):
    """CheckStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckStatus(self):
        """Test CheckStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flyio.models.check_status.CheckStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
