# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flyio
from flyio.models.machine_version import MachineVersion  # noqa: E501
from flyio.rest import ApiException


class TestMachineVersion(unittest.TestCase):
    """MachineVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMachineVersion(self):
        """Test MachineVersion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flyio.models.machine_version.MachineVersion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
