# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flyio
from flyio.api.machines_api import MachinesApi  # noqa: E501
from flyio.rest import ApiException


class TestMachinesApi(unittest.TestCase):
    """MachinesApi unit test stubs"""

    def setUp(self):
        self.api = flyio.api.machines_api.MachinesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_machines_cordon(self):
        """Test case for machines_cordon

        """
        pass

    def test_machines_create(self):
        """Test case for machines_create

        """
        pass

    def test_machines_create_lease(self):
        """Test case for machines_create_lease

        """
        pass

    def test_machines_delete(self):
        """Test case for machines_delete

        """
        pass

    def test_machines_delete_metadata(self):
        """Test case for machines_delete_metadata

        """
        pass

    def test_machines_exec(self):
        """Test case for machines_exec

        """
        pass

    def test_machines_list(self):
        """Test case for machines_list

        """
        pass

    def test_machines_list_events(self):
        """Test case for machines_list_events

        """
        pass

    def test_machines_list_processes(self):
        """Test case for machines_list_processes

        """
        pass

    def test_machines_list_versions(self):
        """Test case for machines_list_versions

        """
        pass

    def test_machines_release_lease(self):
        """Test case for machines_release_lease

        """
        pass

    def test_machines_restart(self):
        """Test case for machines_restart

        """
        pass

    def test_machines_show(self):
        """Test case for machines_show

        """
        pass

    def test_machines_show_lease(self):
        """Test case for machines_show_lease

        """
        pass

    def test_machines_show_metadata(self):
        """Test case for machines_show_metadata

        """
        pass

    def test_machines_signal(self):
        """Test case for machines_signal

        """
        pass

    def test_machines_start(self):
        """Test case for machines_start

        """
        pass

    def test_machines_stop(self):
        """Test case for machines_stop

        """
        pass

    def test_machines_uncordon(self):
        """Test case for machines_uncordon

        """
        pass

    def test_machines_update(self):
        """Test case for machines_update

        """
        pass

    def test_machines_update_metadata(self):
        """Test case for machines_update_metadata

        """
        pass

    def test_machines_wait(self):
        """Test case for machines_wait

        """
        pass


if __name__ == '__main__':
    unittest.main()
