# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flyio
from flyio.api.apps_api import AppsApi  # noqa: E501
from flyio.rest import ApiException


class TestAppsApi(unittest.TestCase):
    """AppsApi unit test stubs"""

    def setUp(self):
        self.api = flyio.api.apps_api.AppsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apps_create(self):
        """Test case for apps_create

        """
        pass

    def test_apps_delete(self):
        """Test case for apps_delete

        """
        pass

    def test_apps_list(self):
        """Test case for apps_list

        """
        pass

    def test_apps_show(self):
        """Test case for apps_show

        """
        pass


if __name__ == '__main__':
    unittest.main()
