# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flyio
from flyio.api.volumes_api import VolumesApi  # noqa: E501
from flyio.rest import ApiException


class TestVolumesApi(unittest.TestCase):
    """VolumesApi unit test stubs"""

    def setUp(self):
        self.api = flyio.api.volumes_api.VolumesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_volume_snapshot(self):
        """Test case for create_volume_snapshot

        """
        pass

    def test_volume_delete(self):
        """Test case for volume_delete

        """
        pass

    def test_volumes_create(self):
        """Test case for volumes_create

        """
        pass

    def test_volumes_extend(self):
        """Test case for volumes_extend

        """
        pass

    def test_volumes_get_by_id(self):
        """Test case for volumes_get_by_id

        """
        pass

    def test_volumes_list(self):
        """Test case for volumes_list

        """
        pass

    def test_volumes_list_snapshots(self):
        """Test case for volumes_list_snapshots

        """
        pass

    def test_volumes_update(self):
        """Test case for volumes_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
