# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from flyio.configuration import Configuration


class ApiMachineInit(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cmd': 'list[str]',
        'entrypoint': 'list[str]',
        '_exec': 'list[str]',
        'kernel_args': 'list[str]',
        'swap_size_mb': 'int',
        'tty': 'bool'
    }

    attribute_map = {
        'cmd': 'cmd',
        'entrypoint': 'entrypoint',
        '_exec': 'exec',
        'kernel_args': 'kernel_args',
        'swap_size_mb': 'swap_size_mb',
        'tty': 'tty'
    }

    def __init__(self, cmd=None, entrypoint=None, _exec=None, kernel_args=None, swap_size_mb=None, tty=None, _configuration=None):  # noqa: E501
        """ApiMachineInit - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._cmd = None
        self._entrypoint = None
        self.__exec = None
        self._kernel_args = None
        self._swap_size_mb = None
        self._tty = None
        self.discriminator = None

        if cmd is not None:
            self.cmd = cmd
        if entrypoint is not None:
            self.entrypoint = entrypoint
        if _exec is not None:
            self._exec = _exec
        if kernel_args is not None:
            self.kernel_args = kernel_args
        if swap_size_mb is not None:
            self.swap_size_mb = swap_size_mb
        if tty is not None:
            self.tty = tty

    @property
    def cmd(self):
        """Gets the cmd of this ApiMachineInit.  # noqa: E501


        :return: The cmd of this ApiMachineInit.  # noqa: E501
        :rtype: list[str]
        """
        return self._cmd

    @cmd.setter
    def cmd(self, cmd):
        """Sets the cmd of this ApiMachineInit.


        :param cmd: The cmd of this ApiMachineInit.  # noqa: E501
        :type: list[str]
        """

        self._cmd = cmd

    @property
    def entrypoint(self):
        """Gets the entrypoint of this ApiMachineInit.  # noqa: E501


        :return: The entrypoint of this ApiMachineInit.  # noqa: E501
        :rtype: list[str]
        """
        return self._entrypoint

    @entrypoint.setter
    def entrypoint(self, entrypoint):
        """Sets the entrypoint of this ApiMachineInit.


        :param entrypoint: The entrypoint of this ApiMachineInit.  # noqa: E501
        :type: list[str]
        """

        self._entrypoint = entrypoint

    @property
    def _exec(self):
        """Gets the _exec of this ApiMachineInit.  # noqa: E501


        :return: The _exec of this ApiMachineInit.  # noqa: E501
        :rtype: list[str]
        """
        return self.__exec

    @_exec.setter
    def _exec(self, _exec):
        """Sets the _exec of this ApiMachineInit.


        :param _exec: The _exec of this ApiMachineInit.  # noqa: E501
        :type: list[str]
        """

        self.__exec = _exec

    @property
    def kernel_args(self):
        """Gets the kernel_args of this ApiMachineInit.  # noqa: E501


        :return: The kernel_args of this ApiMachineInit.  # noqa: E501
        :rtype: list[str]
        """
        return self._kernel_args

    @kernel_args.setter
    def kernel_args(self, kernel_args):
        """Sets the kernel_args of this ApiMachineInit.


        :param kernel_args: The kernel_args of this ApiMachineInit.  # noqa: E501
        :type: list[str]
        """

        self._kernel_args = kernel_args

    @property
    def swap_size_mb(self):
        """Gets the swap_size_mb of this ApiMachineInit.  # noqa: E501


        :return: The swap_size_mb of this ApiMachineInit.  # noqa: E501
        :rtype: int
        """
        return self._swap_size_mb

    @swap_size_mb.setter
    def swap_size_mb(self, swap_size_mb):
        """Sets the swap_size_mb of this ApiMachineInit.


        :param swap_size_mb: The swap_size_mb of this ApiMachineInit.  # noqa: E501
        :type: int
        """

        self._swap_size_mb = swap_size_mb

    @property
    def tty(self):
        """Gets the tty of this ApiMachineInit.  # noqa: E501


        :return: The tty of this ApiMachineInit.  # noqa: E501
        :rtype: bool
        """
        return self._tty

    @tty.setter
    def tty(self, tty):
        """Sets the tty of this ApiMachineInit.


        :param tty: The tty of this ApiMachineInit.  # noqa: E501
        :type: bool
        """

        self._tty = tty

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiMachineInit, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiMachineInit):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiMachineInit):
            return True

        return self.to_dict() != other.to_dict()
