# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from flyio.configuration import Configuration


class ApiHTTPOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'compress': 'bool',
        'h2_backend': 'bool',
        'response': 'ApiHTTPResponseOptions'
    }

    attribute_map = {
        'compress': 'compress',
        'h2_backend': 'h2_backend',
        'response': 'response'
    }

    def __init__(self, compress=None, h2_backend=None, response=None, _configuration=None):  # noqa: E501
        """ApiHTTPOptions - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._compress = None
        self._h2_backend = None
        self._response = None
        self.discriminator = None

        if compress is not None:
            self.compress = compress
        if h2_backend is not None:
            self.h2_backend = h2_backend
        if response is not None:
            self.response = response

    @property
    def compress(self):
        """Gets the compress of this ApiHTTPOptions.  # noqa: E501


        :return: The compress of this ApiHTTPOptions.  # noqa: E501
        :rtype: bool
        """
        return self._compress

    @compress.setter
    def compress(self, compress):
        """Sets the compress of this ApiHTTPOptions.


        :param compress: The compress of this ApiHTTPOptions.  # noqa: E501
        :type: bool
        """

        self._compress = compress

    @property
    def h2_backend(self):
        """Gets the h2_backend of this ApiHTTPOptions.  # noqa: E501


        :return: The h2_backend of this ApiHTTPOptions.  # noqa: E501
        :rtype: bool
        """
        return self._h2_backend

    @h2_backend.setter
    def h2_backend(self, h2_backend):
        """Sets the h2_backend of this ApiHTTPOptions.


        :param h2_backend: The h2_backend of this ApiHTTPOptions.  # noqa: E501
        :type: bool
        """

        self._h2_backend = h2_backend

    @property
    def response(self):
        """Gets the response of this ApiHTTPOptions.  # noqa: E501


        :return: The response of this ApiHTTPOptions.  # noqa: E501
        :rtype: ApiHTTPResponseOptions
        """
        return self._response

    @response.setter
    def response(self, response):
        """Sets the response of this ApiHTTPOptions.


        :param response: The response of this ApiHTTPOptions.  # noqa: E501
        :type: ApiHTTPResponseOptions
        """

        self._response = response

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiHTTPOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiHTTPOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiHTTPOptions):
            return True

        return self.to_dict() != other.to_dict()
