# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from flyio.configuration import Configuration


class ApiFile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'guest_path': 'str',
        'raw_value': 'str',
        'secret_name': 'str'
    }

    attribute_map = {
        'guest_path': 'guest_path',
        'raw_value': 'raw_value',
        'secret_name': 'secret_name'
    }

    def __init__(self, guest_path=None, raw_value=None, secret_name=None, _configuration=None):  # noqa: E501
        """ApiFile - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._guest_path = None
        self._raw_value = None
        self._secret_name = None
        self.discriminator = None

        if guest_path is not None:
            self.guest_path = guest_path
        if raw_value is not None:
            self.raw_value = raw_value
        if secret_name is not None:
            self.secret_name = secret_name

    @property
    def guest_path(self):
        """Gets the guest_path of this ApiFile.  # noqa: E501

        GuestPath is the path on the machine where the file will be written and must be an absolute path. For example: /full/path/to/file.json  # noqa: E501

        :return: The guest_path of this ApiFile.  # noqa: E501
        :rtype: str
        """
        return self._guest_path

    @guest_path.setter
    def guest_path(self, guest_path):
        """Sets the guest_path of this ApiFile.

        GuestPath is the path on the machine where the file will be written and must be an absolute path. For example: /full/path/to/file.json  # noqa: E501

        :param guest_path: The guest_path of this ApiFile.  # noqa: E501
        :type: str
        """

        self._guest_path = guest_path

    @property
    def raw_value(self):
        """Gets the raw_value of this ApiFile.  # noqa: E501

        The base64 encoded string of the file contents.  # noqa: E501

        :return: The raw_value of this ApiFile.  # noqa: E501
        :rtype: str
        """
        return self._raw_value

    @raw_value.setter
    def raw_value(self, raw_value):
        """Sets the raw_value of this ApiFile.

        The base64 encoded string of the file contents.  # noqa: E501

        :param raw_value: The raw_value of this ApiFile.  # noqa: E501
        :type: str
        """

        self._raw_value = raw_value

    @property
    def secret_name(self):
        """Gets the secret_name of this ApiFile.  # noqa: E501

        The name of the secret that contains the base64 encoded file contents.  # noqa: E501

        :return: The secret_name of this ApiFile.  # noqa: E501
        :rtype: str
        """
        return self._secret_name

    @secret_name.setter
    def secret_name(self, secret_name):
        """Sets the secret_name of this ApiFile.

        The name of the secret that contains the base64 encoded file contents.  # noqa: E501

        :param secret_name: The secret_name of this ApiFile.  # noqa: E501
        :type: str
        """

        self._secret_name = secret_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiFile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiFile):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiFile):
            return True

        return self.to_dict() != other.to_dict()
