# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from flyio.configuration import Configuration


class ApiStatic(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'guest_path': 'str',
        'url_prefix': 'str'
    }

    attribute_map = {
        'guest_path': 'guest_path',
        'url_prefix': 'url_prefix'
    }

    def __init__(self, guest_path=None, url_prefix=None, _configuration=None):  # noqa: E501
        """ApiStatic - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._guest_path = None
        self._url_prefix = None
        self.discriminator = None

        self.guest_path = guest_path
        self.url_prefix = url_prefix

    @property
    def guest_path(self):
        """Gets the guest_path of this ApiStatic.  # noqa: E501


        :return: The guest_path of this ApiStatic.  # noqa: E501
        :rtype: str
        """
        return self._guest_path

    @guest_path.setter
    def guest_path(self, guest_path):
        """Sets the guest_path of this ApiStatic.


        :param guest_path: The guest_path of this ApiStatic.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and guest_path is None:
            raise ValueError("Invalid value for `guest_path`, must not be `None`")  # noqa: E501

        self._guest_path = guest_path

    @property
    def url_prefix(self):
        """Gets the url_prefix of this ApiStatic.  # noqa: E501


        :return: The url_prefix of this ApiStatic.  # noqa: E501
        :rtype: str
        """
        return self._url_prefix

    @url_prefix.setter
    def url_prefix(self, url_prefix):
        """Sets the url_prefix of this ApiStatic.


        :param url_prefix: The url_prefix of this ApiStatic.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and url_prefix is None:
            raise ValueError("Invalid value for `url_prefix`, must not be `None`")  # noqa: E501

        self._url_prefix = url_prefix

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiStatic, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiStatic):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiStatic):
            return True

        return self.to_dict() != other.to_dict()
