# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from flyio.configuration import Configuration


class CreateAppRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'app_name': 'str',
        'app_role_id': 'str',
        'network': 'str',
        'org_slug': 'str'
    }

    attribute_map = {
        'app_name': 'app_name',
        'app_role_id': 'app_role_id',
        'network': 'network',
        'org_slug': 'org_slug'
    }

    def __init__(self, app_name=None, app_role_id=None, network=None, org_slug=None, _configuration=None):  # noqa: E501
        """CreateAppRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._app_name = None
        self._app_role_id = None
        self._network = None
        self._org_slug = None
        self.discriminator = None

        if app_name is not None:
            self.app_name = app_name
        if app_role_id is not None:
            self.app_role_id = app_role_id
        if network is not None:
            self.network = network
        if org_slug is not None:
            self.org_slug = org_slug

    @property
    def app_name(self):
        """Gets the app_name of this CreateAppRequest.  # noqa: E501


        :return: The app_name of this CreateAppRequest.  # noqa: E501
        :rtype: str
        """
        return self._app_name

    @app_name.setter
    def app_name(self, app_name):
        """Sets the app_name of this CreateAppRequest.


        :param app_name: The app_name of this CreateAppRequest.  # noqa: E501
        :type: str
        """

        self._app_name = app_name

    @property
    def app_role_id(self):
        """Gets the app_role_id of this CreateAppRequest.  # noqa: E501


        :return: The app_role_id of this CreateAppRequest.  # noqa: E501
        :rtype: str
        """
        return self._app_role_id

    @app_role_id.setter
    def app_role_id(self, app_role_id):
        """Sets the app_role_id of this CreateAppRequest.


        :param app_role_id: The app_role_id of this CreateAppRequest.  # noqa: E501
        :type: str
        """

        self._app_role_id = app_role_id

    @property
    def network(self):
        """Gets the network of this CreateAppRequest.  # noqa: E501


        :return: The network of this CreateAppRequest.  # noqa: E501
        :rtype: str
        """
        return self._network

    @network.setter
    def network(self, network):
        """Sets the network of this CreateAppRequest.


        :param network: The network of this CreateAppRequest.  # noqa: E501
        :type: str
        """

        self._network = network

    @property
    def org_slug(self):
        """Gets the org_slug of this CreateAppRequest.  # noqa: E501


        :return: The org_slug of this CreateAppRequest.  # noqa: E501
        :rtype: str
        """
        return self._org_slug

    @org_slug.setter
    def org_slug(self, org_slug):
        """Sets the org_slug of this CreateAppRequest.


        :param org_slug: The org_slug of this CreateAppRequest.  # noqa: E501
        :type: str
        """

        self._org_slug = org_slug

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateAppRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateAppRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateAppRequest):
            return True

        return self.to_dict() != other.to_dict()
