# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from flyio.configuration import Configuration


class Lease(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'expires_at': 'int',
        'nonce': 'str',
        'owner': 'str',
        'version': 'str'
    }

    attribute_map = {
        'description': 'description',
        'expires_at': 'expires_at',
        'nonce': 'nonce',
        'owner': 'owner',
        'version': 'version'
    }

    def __init__(self, description=None, expires_at=None, nonce=None, owner=None, version=None, _configuration=None):  # noqa: E501
        """Lease - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._description = None
        self._expires_at = None
        self._nonce = None
        self._owner = None
        self._version = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if expires_at is not None:
            self.expires_at = expires_at
        if nonce is not None:
            self.nonce = nonce
        if owner is not None:
            self.owner = owner
        if version is not None:
            self.version = version

    @property
    def description(self):
        """Gets the description of this Lease.  # noqa: E501

        Description or reason for the Lease.  # noqa: E501

        :return: The description of this Lease.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Lease.

        Description or reason for the Lease.  # noqa: E501

        :param description: The description of this Lease.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def expires_at(self):
        """Gets the expires_at of this Lease.  # noqa: E501

        ExpiresAt is the unix timestamp in UTC to denote when the Lease will no longer be valid.  # noqa: E501

        :return: The expires_at of this Lease.  # noqa: E501
        :rtype: int
        """
        return self._expires_at

    @expires_at.setter
    def expires_at(self, expires_at):
        """Sets the expires_at of this Lease.

        ExpiresAt is the unix timestamp in UTC to denote when the Lease will no longer be valid.  # noqa: E501

        :param expires_at: The expires_at of this Lease.  # noqa: E501
        :type: int
        """

        self._expires_at = expires_at

    @property
    def nonce(self):
        """Gets the nonce of this Lease.  # noqa: E501

        Nonce is the unique ID autogenerated and associated with the Lease.  # noqa: E501

        :return: The nonce of this Lease.  # noqa: E501
        :rtype: str
        """
        return self._nonce

    @nonce.setter
    def nonce(self, nonce):
        """Sets the nonce of this Lease.

        Nonce is the unique ID autogenerated and associated with the Lease.  # noqa: E501

        :param nonce: The nonce of this Lease.  # noqa: E501
        :type: str
        """

        self._nonce = nonce

    @property
    def owner(self):
        """Gets the owner of this Lease.  # noqa: E501

        Owner is the user identifier which acquired the Lease.  # noqa: E501

        :return: The owner of this Lease.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this Lease.

        Owner is the user identifier which acquired the Lease.  # noqa: E501

        :param owner: The owner of this Lease.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def version(self):
        """Gets the version of this Lease.  # noqa: E501

        Machine version  # noqa: E501

        :return: The version of this Lease.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this Lease.

        Machine version  # noqa: E501

        :param version: The version of this Lease.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Lease, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Lease):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Lease):
            return True

        return self.to_dict() != other.to_dict()
