# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from flyio.configuration import Configuration


class ListApp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'machine_count': 'int',
        'name': 'str',
        'network': 'object'
    }

    attribute_map = {
        'id': 'id',
        'machine_count': 'machine_count',
        'name': 'name',
        'network': 'network'
    }

    def __init__(self, id=None, machine_count=None, name=None, network=None, _configuration=None):  # noqa: E501
        """ListApp - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._machine_count = None
        self._name = None
        self._network = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if machine_count is not None:
            self.machine_count = machine_count
        if name is not None:
            self.name = name
        if network is not None:
            self.network = network

    @property
    def id(self):
        """Gets the id of this ListApp.  # noqa: E501


        :return: The id of this ListApp.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ListApp.


        :param id: The id of this ListApp.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def machine_count(self):
        """Gets the machine_count of this ListApp.  # noqa: E501


        :return: The machine_count of this ListApp.  # noqa: E501
        :rtype: int
        """
        return self._machine_count

    @machine_count.setter
    def machine_count(self, machine_count):
        """Sets the machine_count of this ListApp.


        :param machine_count: The machine_count of this ListApp.  # noqa: E501
        :type: int
        """

        self._machine_count = machine_count

    @property
    def name(self):
        """Gets the name of this ListApp.  # noqa: E501


        :return: The name of this ListApp.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ListApp.


        :param name: The name of this ListApp.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def network(self):
        """Gets the network of this ListApp.  # noqa: E501


        :return: The network of this ListApp.  # noqa: E501
        :rtype: object
        """
        return self._network

    @network.setter
    def network(self, network):
        """Sets the network of this ListApp.


        :param network: The network of this ListApp.  # noqa: E501
        :type: object
        """

        self._network = network

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListApp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListApp):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListApp):
            return True

        return self.to_dict() != other.to_dict()
